### ISSUE TITLE
bbPress: Emoji saved as images

### ISSUE THREAD

**Issue by dd32** [Automattic/gutenberg-everywhere#111]
Although not the worst thing, when Emoji is inserted into a reply in the Block Editor and `wp-emoji` is loaded on the page, `wp-emoji` will alter the entered emojis into `img.emoji` if appropriate.

Upon save, this saves as `img.emoji` elements rather than as emoji's.

#107 whitelisted the class attribute for emojis, so that they don't end up as large image embeds, but this causes other emoji-replacement atributes to be lost (such as `role` and `alt`).

See https://meta.trac.wordpress.org/changeset/12341 for some reversing I've applied on the WordPress.org forums.

Unfortunately, it's not possible to exclude wp-emoji from processing the editor content, without adding `.wp-exclude-emoji` to every element. See https://core.trac.wordpress.org/ticket/52219 for an upstream change to allow it to respect that element on parent nodes.

**Comment by johngodley** [comment]
How is the emoji inserted? I've tried using the MacOS emoji picker but that doesn't seem to work with Gutenberg. I've tried typing `:)` and it gets converted to a smiley, but remains as text in the editor.

**Comment by dd32** [comment]
The best way I've found to use Emoji is to just copy-paste, https://emojiguide.com/symbols/check-mark/ for example.
