### ISSUE TITLE
Fatal error: Uncaught Error: Class 'WP_Theme_JSON_Data_Gutenberg' not found 

### ISSUE THREAD

**Issue by basewire** [Automattic/gutenberg-everywhere#137]
I have activated the WordPress plugin "blocks-everywhere" and the below-noted definitions to the wp-config.php:

```
define( 'BLOCKS_EVERYWHERE_COMMENTS', true );
define( 'BLOCKS_EVERYWHERE_BBPRESS', true );
define( 'BLOCKS_EVERYWHERE_BUDDYPRESS', true );
define( 'BLOCKS_EVERYWHERE_ADMIN', true );
define( 'BLOCKS_EVERYWHERE_BBPRESS_ADMIN', true );
define( 'BLOCKS_EVERYWHERE_THEME_COMPAT', true );
```

Also added this to the functions.php for allowing the paragraph block.

```
add_filter( 'blocks_everywhere_editor_settings', function( $settings ) {
	$settings['iso']['blocks']['allowBlocks'][] = 'core/paragraph';
    return $settings;
} );

add_filter( 'blocks_everywhere_admin', '__return_true' );
add_filter( 'blocks_everywhere_admin_cap', '__return_empty_string' );
```

But after visiting a bbPress forum page I'm getting this error as a return:

```
Fatal error: Uncaught Error: Class 'WP_Theme_JSON_Data_Gutenberg' not found in /*****/wp-content/plugins/blocks-everywhere/classes/class-editor.php on line 33
```

And:

```
Error: Class 'WP_Theme_JSON_Data_Gutenberg' not found in /*****/wp-content/plugins/blocks-everywhere/classes/class-editor.php on line 33
```

The theme.json is available in the theme. Is this a know situation or did I miss a setting?

**Comment by johngodley** [comment]
No this is not a known situation. What version of WP are you using? What version of Gutenberg are you using?

**Comment by basewire** [comment]
WordPress - 6.1.1
Gutenberg - Not installed

I Thought WordPress core has Gutenberg already included in the core after 6.0? This why I didn't installed the extra Gutenberg plugin. But after installing the Gutenberg plugin the blocks-everywhere plugin and settings are working :)

**Comment by johngodley** [comment]
The plugin requires Gutenberg to be installed as a plugin. It's mentioned briefly in the readme, and is needed because the version in WP is generally quite old and doesn't have the features needed.

**Comment by basewire** [comment]
I see, thought there was no different between the versions but this clarify it for me. Thank you for your fast reply and helping me out,
