### ISSUE TITLE
The submit button for a link is white on white when you try to click it,

### ISSUE THREAD

**Issue by sterndata** [Automattic/gutenberg-everywhere#144]
The submit button for a link is white on white when you try to click it, and the little arrow indicating "return" is gone.

https://www.loom.com/share/49c322357cb24beea1c06cd8be1eeb5e

**Comment by Otto42** [comment]
For reference, this was noticed on the WordPress.org forums.

**Comment by johngodley** [comment]
This seems to be something new in Gutenberg 15.1, which hasn't been tested yet. I'll look into it.

**Comment by johngodley** [comment]
> the little arrow indicating "return" is gone.

This has been removed in Gutenberg.
