### ISSUE TITLE
Code tag styles are only applied within p tags

### ISSUE THREAD

**Issue by t-hamano** [Automattic/gutenberg-everywhere#150]
Reported in Gutenberg Project: [Transforming paragraph to list item → Inline code then falsely shown as normal text #48627](https://github.com/WordPress/gutenberg/issues/48627)

When inline code is applied to the text, a gray background color is applied by the CSS in this plugin. However, because [its selector is limited to the p element](https://github.com/Automattic/blocks-everywhere/blob/0550f066a96d6f88a20a9ef9c842ce02b6a55b45/src/styles/theme-compat.scss#L194), the style is not applied to code tags in list items, for example.
 t is difficult to determine if this is a bug or not, but personally, I think it would be good to apply it to all blocks that have rich text.

![blocks-everywhere](https://user-images.githubusercontent.com/54422211/222318254-5b93bbdd-1bdd-4334-b031-3eea2eaa1b89.png)

**Comment by porg** [comment]
It clearly is a bug because the "inline" in "inline code" clearly dictates that this style should be applied everywhere it appears, be it a paragraph, list item, quote, etc.

**Comment by porg** [comment]
Thanks!

- CSS selector is now: `.editor-styles-wrapper` **`.wp-block`** `code`
- Learned from this that `.wp-block` is the most specifically possible selector here.
