### ISSUE TITLE
URLs within code blocks should not oEmbed

### ISSUE THREAD

**Issue by bcworkz-wp** [Automattic/gutenberg-everywhere#154]
The point of a code block is to show original source code. If oEmbed is applied, it obscures the original source code.
Example forum post: https://wordpress.org/support/topic/using-link-to-youtube-option-it-does-not-work-with-videos-classified-as-shorts/
In this particular post, oEmbed actually being applied helps make the OP's point, but in general it's an undesirable "feature". The OP also probably never intended to use a code block, I think it was auto-applied because they pasted in the entire topic's content. Application of auto-code is a separate issue external to blocks everywhere.

**Comment by johngodley** [comment]
Sorry, I don't really understand what you mean. This all seems standard Gutenberg/WordPress behaviour. Is this something that the plugin is doing differently to Gutenberg/WP?

**Comment by bcworkz-wp** [comment]
AFAICT URLs in standard Gutenberg/WordPress code blocks do not oEmbed. I just verified on my WP test site. However, they do oEmbed in the forum's code blocks while using tinyMCE as well, so it's not the blocks everywhere plugin after all. Closing, thanks for helping get my thoughts in order.

Already an issue being tracked in meta.trac: https://core.trac.wordpress.org/ticket/39472
