### ISSUE TITLE
Possible to add to selected textareas?

### ISSUE THREAD

**Issue by ehausen** [Automattic/gutenberg-everywhere#169]
Is it possible to add standalone Gutenberg editor to ACF rich content field? Right now it is possible to have custom fields with TinyMCE or similar, but how to replace that with Gutenberg?

_The Plain Text Editor_ -link in Readme goes to "Not found" ( /isolated-block-editor/src/browser/README.md )

**Comment by johngodley** [comment]
See #143 for more details about ACF
