### ISSUE TITLE
Doesn't work with the standalone Gutenberg Plugin activated.

### ISSUE THREAD

**Issue by SGr33n** [Automattic/gutenberg-everywhere#171]
I'm just testing Blocks Everywhere and I see that doesn't if the Gutenberg standalone plugin is activated. The error is:

```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
i @react-dom.js?ver=18:1

```
I also tested the 1.18, where there is also a deprecation warning, but it's pretty simple to solve.

**Comment by johngodley** [comment]
The plugin requires the standalone Gutenberg plugin, but it won't work yet with Gutenberg 15.5.0+. The above message is just a warning. Specifically what isn't working for you?

**Comment by SGr33n** [comment]
Ok so it won't work with 15.5.0+, I'm using 15.5.1.
The editor fails to initialize... it's remaining grey.

Thanks!

**Comment by johngodley** [comment]
Version 1.18.0 is now compatible with Gutenberg 15.5.0+
