### ISSUE TITLE
Compatibility issue with 1.21.0 and Gutenberg 16.9 

### ISSUE THREAD

**Issue by adamwoodnz** [Automattic/gutenberg-everywhere#192]
The editor broke on the WordPress.org support forums yesterday after Gutenberg upgraded to 16.9.

See https://wordpress.slack.com/archives/C02QB8GMM/p1698271643977769

Error message as captured by OP

![err](https://github.com/Automattic/blocks-everywhere/assets/1017872/ca69c88f-f913-489c-88c6-5b38a66e2cce)

Rolling back Gutenberg to 16.8.1 has fixed the issue for now.

**Comment by johngodley** [comment]
Unfortunatley I think because of how Gutenberg now implements private APIs this will probably happen each time a new version is released.

**Comment by iandunn** [comment]
Is there something they could change upstream that would prevent this? Or do you have any ideas on how to work around it?

**Comment by adamwoodnz** [comment]
It looks like we can upgrade to 16.9, but no further: https://github.com/Automattic/blocks-everywhere/pull/193

**Comment by adamwoodnz** [comment]
Tested 16.9 and other things break, so looks like we're stuck on 16.8.1 for the time being.

**Comment by dd32** [comment]
I'm closing this, as more recent versions of the plugin appear to support more recent versions of Gutenberg.
