### ISSUE TITLE
Accessibility issue on `components-dropdown-menu__toggle` button inside support forum customised editor

### ISSUE THREAD

**Issue by heybran** [Automattic/gutenberg-everywhere#197]
Hello, I'm reporting an accessibility issue that I found when I was answering questions on support forum. Inside this customised editor, this toggle button `components-dropdown-menu__toggle ` as shown per screenshot below is barely noticeable, tested on Chrome 119.0 and Safari 17.1

![Screenshot-2023-11-23-at-10-52-22](https://github.com/Automattic/blocks-everywhere/assets/75633537/738897fa-0e71-46a3-9590-f44dc4f4b3dd)

**Comment by johngodley** [comment]
It's just a CSS bug. It will be fixed in the next release.
