### ISSUE TITLE
Twenty Twenty-Four theme, usntable API warning ?

### ISSUE THREAD

**Issue by sinanisler** [Automattic/gutenberg-everywhere#198]
failed to make it work with Twenty Twenty-Four theme and in the comments.

made the wp-config setups

using;
WordPress 6.4.1
Gutenberg 17.1.4
Twenty-Four theme

![image](https://github.com/Automattic/blocks-everywhere/assets/1686324/a5fbca72-5d1a-4c35-9c87-81381354c843)

hmmm

**Comment by johngodley** [comment]
As detailed in the readme:

`* Update for Gutenberg 16.9. Now only works with this specific version.`
