### ISSUE TITLE
Color confilct with code block on new WP forum design

### ISSUE THREAD

**Issue by KevinBatdorf** [Automattic/gutenberg-everywhere#202]
The new update changed the bg color of the `<pre>` tag which conflicts with the bg color on the code tag here:

https://github.com/Automattic/blocks-everywhere/blob/trunk/src/styles/theme-compat.scss#L194

![CleanShot 2024-04-11 at 02 20 14@2x](https://github.com/Automattic/blocks-everywhere/assets/1478421/0bfd6db2-46bb-49dc-8f67-28a991c9ef79)

Not sure why the difference but also rendered like this once

![CleanShot 2024-04-11 at 02 21 22@2x](https://github.com/Automattic/blocks-everywhere/assets/1478421/5d60b763-e6cf-4454-b149-259a337488e6)

**Comment by ndiego** [comment]
cc @adamwoodnz
