### ISSUE TITLE
Plugin is broken in Wordpress 5.9 RC.1

### ISSUE THREAD

**Issue by ghost** [Automattic/gutenberg-everywhere#21]
The frontend block editors display an error with the following output:

cFS5/C/<@https://gutenburg.local/wp-includes/js/dist/keyboard-shortcuts.min.js?ver=77c30626bb8cf4f5306643107664a1ae:2:3817
Tj@https://gutenburg.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:179:399
unstable_runWithPriority@https://gutenburg.local/wp-includes/js/dist/vendor/react.min.js?ver=17.0.1:24:26
Za@https://gutenburg.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:8
Ra@https://gutenburg.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:178:368
gf@https://gutenburg.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:161:497
$g/<@https://gutenburg.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:230
unstable_runWithPriority@https://gutenburg.local/wp-includes/js/dist/vendor/react.min.js?ver=17.0.1:24:26
Za@https://gutenburg.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:8
$g@https://gutenburg.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:178
ja@https://gutenburg.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:111
Tj@https://gutenburg.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:180:72
unstable_runWithPriority@https://gutenburg.local/wp-includes/js/dist/vendor/react.min.js?ver=17.0.1:24:26
Za@https://gutenburg.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:8
Ra@https://gutenburg.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:178:368
Rj/<@https://gutenburg.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:178:275
R@https://gutenburg.local/wp-includes/js/dist/vendor/react.min.js?ver=17.0.1:16:299
ua.port1.onmessage@https://gutenburg.local/wp-includes/js/dist/vendor/react.min.js?ver=17.0.1:22:361
![Screenshot 2022-01-10 at 12-48-47 Activity – a – gutenburg](https://user-images.githubusercontent.com/52989917/148813916-854a15c3-4f27-4c85-831b-e6e7236ad5e1.png)

**Comment by johngodley** [comment]
This should be fixed in 1.3.0
