### ISSUE TITLE
Missing search box

### ISSUE THREAD

**Issue by ghost** [Automattic/gutenberg-everywhere#23]
When I first add a block by using the right '+', I can add so many blocks by searching like:
![QQ20220209-114947](https://user-images.githubusercontent.com/45513686/153118630-f7d4381a-4f61-417d-ba69-3dccc98e2cbd.png)
Even YouTube:
![QQ20220209-115007](https://user-images.githubusercontent.com/45513686/153118711-460826f9-6e60-470c-ae74-bf0409e186ba.png)
But when I try to add the second block, the search box missing.
![QQ20220209-115035](https://user-images.githubusercontent.com/45513686/153118818-e927b559-5fae-4a74-a3a9-e1e449a8c8ec.png)
Is it a bug? How could I fix it?

**Comment by johngodley** [comment]
This probably just needs to be updated for a more recent Gutenberg.
