### ISSUE TITLE
Breaking change coming in Gutenberg Core

### ISSUE THREAD

**Issue by getdave** [Automattic/gutenberg-everywhere#25]
It looks like this uses `__experimentalFetchLinkSuggestions` which is about to be promoted to a stable API.

Just flagging the PR so you're ready for it:

https://github.com/WordPress/gutenberg/pull/40052

**Comment by akirk** [comment]
This function seems to be called inside the dependency https://github.com/Automattic/isolated-block-editor and seems to have been used in a way that expects its deprecation/rename: https://github.com/Automattic/isolated-block-editor/blob/a9650f4660553339583bb097102fd2066ec9b3e1/src/components/default-settings/index.js#L137-L140

**Comment by johngodley** [comment]
Closing as done.
