### ISSUE TITLE
Plugin not working after update

### ISSUE THREAD

**Issue by derintolu** [Automattic/gutenberg-everywhere#34]
So after this update, activating the plugin doesn't replace any of the text boxes like it did before.

**Comment by johngodley** [comment]
Can you provide more details? Which text boxes? Which feature are you referring to - comments, bbpress, buddypress? Do you have any browser console errors?

**Comment by derintolu** [comment]
Im on wordpress 6.1. Using twenty-twenty three on a fresh install. It's like the plugin isnt even active. There are no console errors. Comments hasnt shifted to the block editor and neither has the activity editor. Its seems like the plugin isnt active but it shows as activated.

**Comment by johngodley** [comment]
You will need to read the usage instructions here:

https://github.com/Automattic/blocks-everywhere/blob/trunk/readme.txt

**Comment by derintolu** [comment]
I see. I had it installed on another site when it was gutenberg everywhere. I didnt see the change my bad.

**Comment by johngodley** [comment]
Sorry, yes, the plugin is being made ready to go onto wordpress.org and a lot of breaking changes are being made. Once it's properly available it will be less experimental.
