### ISSUE TITLE
bbPress: When editing old posts with Classic Editor Block, full Kitchen Sink is shown

### ISSUE THREAD

**Issue by dd32** [Automattic/gutenberg-everywhere#44]
bbPress uses a minimal editor and supports a minimal set of tags, but when an existing post is edited with Blocks Everywhere enabled, the full "Kitchen Sink" TinyMCE editor is loaded.

This provides editing functionality which the user can use, but will be broken upon save.
Including the Media Inserter functionality.

This might be more of an issue with Upstream Gutenberg?
Ideally, the TinyMCE editor would not be loaded, and instead a textarea be present in it's place.

<img width="641" alt="Screen Shot 2022-11-28 at 4 57 52 pm" src="https://user-images.githubusercontent.com/767313/204213533-b70888f0-493e-4cb4-94cf-2dd5eaa8827d.png">

**Comment by johngodley** [comment]
A good point. Unfortunately I don't think it's possible to stop Gutenberg using TinyMCE. In #47 I've disabled most of the toolbar, which seems to be enough to prevent any issues here.
