### ISSUE TITLE
bbPress: Convert to Blocks doesn't work

### ISSUE THREAD

**Issue by dd32** [Automattic/gutenberg-everywhere#45]
When editing non-block threads/replies, the `Convert to blocks` button doesn't do anything.

https://user-images.githubusercontent.com/767313/204218532-1cc0fb6a-5219-40cb-9c88-fa4418df87e8.mov

**Comment by johngodley** [comment]
Interesting. I think there may be something else going on here as it works in all the testing environments I've tried. Could you do `JSON.stringify( wpBlocksEverywhere )` from the browser console and upload the results somewhere? I wonder if there's a configuration difference.

**Comment by dd32** [comment]
As an update; This appears to be caused by having `<pre>` involved in the mix, anything else, including just `<code>..</code>` works.

I can't reproduce it in stand alone Gutenberg.

The raw HTML in this case was:
```
<pre><code>&lt;?php do_stuff();
// This is code.
</code></pre>
<p>Paragraph</p>
```
But this converted fine:
```
<p><code>&lt;?php do_stuff();
// This is code.
</code></p>
<p>Paragraph</p>
```

**Comment by johngodley** [comment]
This still works fine for me. Nothing really stands out in the JSON, or the associated code. Let's see what happens when the plugin is updated - maybe the problem will disappear.

**Comment by johngodley** [comment]
It seems to be content specific. I wasn't able to get the above to fail, but some content with a shortcode in did. I'll look into that some more.

**Comment by johngodley** [comment]
I fixed the problem with shortcodes in https://github.com/Automattic/blocks-everywhere/pull/92. There may be other cases like this which we'll need to look at individually. I think, for now, this is probably fixed.

**Comment by johngodley** [comment]
Closing this as fixed.
