### ISSUE TITLE
Better support for long messages

### ISSUE THREAD

**Issue by johngodley** [Automattic/gutenberg-everywhere#54]
In some forums people will often paste long messages, such as system and error logs. It would be nice if there was better support for this:
- Don't split into multiple blocks
- Have some kind of text expander where the majority of text is hidden and expanded out

**Comment by johngodley** [comment]
For example: https://wordpress.org/support/topic/the-plus-addons-for-elementor-breaks-elementor/?view=all#post-15601810 and https://wordpress.org/support/topic/the-plus-addons-for-elementor-error/?view=all#post-15549893

**Comment by dd32** [comment]
Worth noting, that on WordPress.org forums we have an expander that applies to `<code>` (well, `<pre>`) and attempt to auto-wrap long pastes into a code block. This doesn't always work, as shown by the examples above.

Example of the code expander: https://wordpress.org/support/topic/long-code-post/

**Comment by johngodley** [comment]
Looking into this some more it's quite tricky due to how smart Gutenberg tries to be with rich text (which is the default on MacOS at least).

- Pasting plain text mostly works and converts to a code block
- Pasting site health doesn't work as Gutenberg thinks its markdown, creates some headings, and fails because the heading block isn't enabled (see https://github.com/WordPress/gutenberg/issues/19036). It also incorrectly adds backticks.
- Pasting from a rich text source works, but converts in strange ways
- Pasting into a code block always works

There doesn't appear to be a way to hook into the Gutenberg paste handler. I'm still trying out a few options here, but it may require an upstream change.

**Comment by dd32** [comment]
> Pasting plain text mostly works and converts to a code block

I wasn't able to duplicate that. Especially not with plain-text that has many paragraph-like blocks. ie. `"Test\nTest\n\nTest\nTest"`.

Pasting into a Code block works as expected.

Pasting from VSCode into a Paragraph block makes each line a new paragraph, and you can't do a 'paste and match style' (nothing happens) or command+shift+V to paste plain-text/match-style.

~That's the same behaviour upstream though.~
Oh.. weird.. Not the same.  
Upstream, pasting from VSCode in plain-text mode inserts as code, but normal splits into paragraphs.
Upstream, pasting from a many-paragraph block, such as the above Test\nTest payload, always splits into paragraphs.. Must be something about the contents of the paste that makes it think it's code or not.


> There doesn't appear to be a way to hook into the Gutenberg paste handler. I'm still trying out a few options here, but it may require an upstream change.

That was my conclusion as well. It seemed that a way to filter the paste handlers is missing upstream, and that ideally, we'd likely add handling at the start of that handler stack to do some custom processing of the pasted data.

**Comment by johngodley** [comment]
I think we've resolved this issue, at least to a reasonable level, and so I'll close this. I've started new issues to look into modifying things upstream and that's likely the best way of improving things.
