### ISSUE TITLE
Control whether new editor appears on a forum and user level

### ISSUE THREAD

**Issue by johngodley** [Automattic/gutenberg-everywhere#55]
It would help to test this plugin on a production site if there was an option to enable/disable the editor for specific forums and users.

Care needs to be taken so that the old editor is not used to edit block content.

**Comment by dd32** [comment]
#65 has broken bbPress posting, if Blocks Everywhere is loaded after the bbPress plugin (ie. if they're both active plugins, not with Blocks Everywhere as a mu-plugin).

See #74
